name: "Automerge"

on:
  pull_request:

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:

      - name: Merge pull request
        uses: pascalgn/automerge-action@v0.11.0
        if: steps.waitforstatuschecks.outputs.status == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: dependencies
          MERGE_FILTER_AUTHOR: dependabot
          MERGE_METHOD: rebase
          MERGE_RETRIES: 10
          MERGE_RETRY_SLEEP: 60
          MERGE_DELETE_BRANCH: true
