name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v3.0.6

  lint:
    strategy:
      fail-fast: false
      matrix:
        linter:
          - flake8
          - black --check .
          - pyupgrade --py3-plus `find . -name "*.py"`
          - isort -c -v .
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: abatilo/actions-poetry@v2.1.0
      - name: Install Dependencies
        run: poetry install
      - run: poetry run ${{ matrix.linter }}

  test:
    strategy:
      fail-fast: false
      matrix:
        versions:
          - python: 3.6
            django: ">=2.2,<3.0"
          - python: 3.6
            django: ">=3.0,<3.1"
          - python: 3.6
            django: ">=3.1,<3.2"

          - python: 3.7
            django: ">=2.2,<3.0"
          - python: 3.7
            django: ">=3.0,<3.1"
          - python: 3.7
            django: ">=3.1,<3.2"

          - python: 3.8
            django: ">=2.2,<3.0"
          - python: 3.8
            django: ">=3.0,<3.1"
          - python: 3.8
            django: ">=3.1,<3.2"

        os:
          - ubuntu-latest
          # - windows-latest
          # - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.versions.python }}
      - uses: abatilo/actions-poetry@v2.1.0
      - name: Install Dependencies
        run: |
          poetry install -E spellcheck
          poetry run pip install "Django${{ matrix.versions.django }}"
      - name: Run Tests
        run: |
          poetry run coverage run manage.py test test_tinymce
          poetry run coverage xml
      - uses: codecov/codecov-action@v1.2.1

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Should match version in .readthedocs.yml
      - uses: abatilo/actions-poetry@v2.1.0
      - name: Install Dependencies
        run: poetry install -E docs
      - name: Build docs
        working-directory: docs
        run: poetry run make html
