name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        versions:
          - python: 3.5
            django: ">=1.11,<2.0"
          - python: 3.5
            django: ">=2.0,<2.1"
          - python: 3.5
            django: ">=2.1,<2.2"
          - python: 3.5
            django: ">=2.2,<3.0"

          - python: 3.6
            django: ">=1.11,<2.0"
          - python: 3.6
            django: ">=2.0,<2.1"
          - python: 3.6
            django: ">=2.1,<2.2"
          - python: 3.6
            django: ">=2.2,<3.0"

          - python: 3.7
            django: ">=1.11,<2.0"
          - python: 3.7
            django: ">=2.0,<2.1"
          - python: 3.7
            django: ">=2.1,<2.2"
          - python: 3.7
            django: ">=2.2,<3.0"

          - python: 3.8
            django: ">=2.2,<3.0"
        os:
          - ubuntu-latest
          # - windows-latest
          # - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.versions.python }}
    - name: Install Dependencies
      run: |
        python -m pip install -U pip
        pip install "Django${{ matrix.versions.django }}"
        pip install -r requirements.txt -r requirements-dev.txt
    - name: Run Tests
      run: coverage run manage.py test test_tinymce
    - name: Upload coverage report
      run: codecov
      env:
        # Note: pull requests from forks don't have access to secrets
        # The codecov CLI degrades nicely when coming from the environment
        # It causes an error if using the -t option
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
